name: "Free Disk Space (CI Action)"
# This is a simplified version of free-disk-space (https://github.com/BRAINSia/free-disk-space).
description: "A configurable GitHub Action to free up disk space on GitHub Actions runners."

# See: https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#branding
branding:
  icon: "trash-2"
  color: "green"

inputs:
  removalmode:
    # See analysis in https://github.com/SUPERCILEX/fuc/tree/master/comparisons
    description: "File removal mode [rmz, rm]"
    required: false
    default: "rmz"

  dotnet:
    description: "Remove .NET runtime"
    required: false
    default: "true"
  haskell:
    description: "Remove Haskell runtime"
    required: false
    default: "true"
  swap-storage:
    description: "Remove swap storage"
    required: false
    default: "true"

runs:
  using: "composite"
  steps:
    - name: Free disk space
      shell: bash
      run: |
        # ======
        # PLATFORM DETECTION & PATH SETUP
        # ======

        OS_TYPE="${{ runner.os }}"

        # Set platform-specific paths
        if [[ "$OS_TYPE" == "Linux" ]]; then
          DOTNET_PATH="/usr/share/dotnet"
          HASKELL_PATH="/opt/ghc"
          HASKELL_PATH2="/usr/local/.ghcup"
          SWAP_PATH="/mnt/swapfile"
          USE_SUDO="sudo"
        elif [[ "$OS_TYPE" == "macOS" ]]; then
          DOTNET_PATH="/usr/local/share/dotnet"
          HASKELL_PATH="/usr/local/opt/ghc"
          HASKELL_PATH2="$HOME/.ghcup"
          SWAP_PATH="/private/var/vm/swapfile*"
          USE_SUDO="sudo"
        elif [[ "$OS_TYPE" == "Windows" ]]; then
          DOTNET_PATH="/c/Program Files/dotnet"
          HASKELL_PATH="/c/ProgramData/chocolatey/lib/ghc"
          HASKELL_PATH2="$HOME/AppData/Roaming/ghcup"
          SWAP_PATH=""  # Not applicable on Windows
          USE_SUDO=""  # No sudo on Windows
        fi

        # ======
        # MACROS
        # ======

        setup_rmz() {
          curl -fsSL --tlsv1.2 --proto '=https' https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash > /dev/null 2>&1
          cargo binstall -qy rmz
          if [[ "$OS_TYPE" != "Windows" ]]; then
            ln -s ~/.cargo/bin/rmz /usr/local/bin/rmz
          fi
        }

        fast_rmdir() {
          # See analysis in https://github.com/SUPERCILEX/fuc/tree/master/comparisons
          #
          if [[ -d "$1" ]] && [[ -n "$1" ]] && [[ ! "$1" = "/" ]] && [[ ! "$1" = "~" ]]; then
            echo "Removing directory: $1"
            case "${{ inputs.removalmode }}" in
              "rmz")
                # Remove with rmz (requires separate download step)
                $USE_SUDO rmz -f "$1" || true
                ;;
              "rm")
                # Remove with a standard Unix command
                $USE_SUDO rm -rf "$1"
                ;;
              "*")
                echo "ERROR: Invalid removalmode specified.  Valid values are [rmz, rm]"
                exit -1
                ;;
            esac
          fi
        }

        list_installed_dpkg() {
          dpkg --get-selections $@ | grep -v deinstall | awk '{print $1}'
        }

        # macro to print a line of equals
        # (silly but works)
        printSeparationLine() {
          str=${1:=}
          num=${2:-80}
          counter=1
          output=""
          while [ $counter -le $num ]
          do
             output="${output}${str}"
             counter=$((counter+1))
          done
          echo "${output}"
        }

        # macro to print output of df with caption
        printDF() {
          caption=${1:-}

          printSeparationLine '=' 80
          echo "${caption}"
          echo ""
          echo "$ df -h /"
          echo ""
          df -h /
          echo "$ df -a /"
          echo ""
          df -a /
          echo "$ df -a"
          echo ""
          df -a
          printSeparationLine '=' 80
        }



        # ======
        # SCRIPT
        # ======

        if [[ ${{ inputs.removalmode }} == 'rmz' ]]; then
          setup_rmz
        fi

        printDF "BEFORE CLEAN-UP:"
        echo ""

        export INITRD=No

        # Option: Remove .NET runtime

        if [[ ${{ inputs.dotnet }} == 'true' ]]; then
          echo "Removing .NET runtime..."
          fast_rmdir "$DOTNET_PATH" || true
        fi

        # Option: Remove Haskell runtime

        if [[ ${{ inputs.haskell }} == 'true' ]]; then
          echo "Removing Haskell runtime..."
          fast_rmdir "$HASKELL_PATH" || true
          fast_rmdir "$HASKELL_PATH2" || true
        fi

        # Option: Remove Swap storage

        if [[ ${{ inputs.swap-storage }} == 'true' ]]; then
          if [[ "$OS_TYPE" == "Windows" ]]; then
            echo "Swap storage removal not applicable on Windows (using pagefile instead)"
          else
            echo "Removing swap storage..."
            if [[ "$OS_TYPE" == "Linux" ]]; then
              $USE_SUDO swapoff -a || true
            fi
            $USE_SUDO rm -f $SWAP_PATH || true
            free -h 2>/dev/null || true
          fi
        fi



        echo ""
        printDF "AFTER CLEAN-UP:"
